name: Compile LibVLC 4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment
        run: |
          export ANDROID_SDK=/usr/local/lib/android/sdk
          export ANDROID_NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653
    
      - name: Clone vlc-android
        run: git clone https://code.videolan.org/videolan/vlc-android.git
        
      - name: Run compile (arm)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -vlc4 -a arm
        
      - name: Run compile (arm64)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -vlc4 -a arm64
        
      - name: Run compile (x86)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -vlc4 -a x86
        
      - name: Run compile (x86_64)
        working-directory: vlc-android
        run: buildsystem/compile.sh -l -r -vlc4 -a x86_64
      
      - name: Archive aar
        uses: actions/upload-artifact@v3
        with:
          name: LibVLCJNI
          path: vlc-android/libvlcjni/libvlc/build/outputs
